notes/git_commands.md

git commands

---

week0/secB/PES2UG22EC115.md

Added my file PES2UG22EC115.md
Sahil S Prabhu - SecB

Added PES2UG22EC115.md

---

week0/secB/PES2UG22EC088.md

added PES2UG22EC088.md

---

week0/secB/PES2UG22EC109.md

PES2UG22EC109.md

---

week0/secB/PES2UG22EC097.txt

Added details

---

week0/secB/PES2UG22EC136.md

PES2UG22EC136

---

week0/secB/PES2UG22EC098.md

Added Credentials

---

week0/secB/PES2UG22EC124.md

PES2UG22EC124

---

week0/secB/PES2UG22EC113.md

added PES2UG22EC113.md

---

week0/secB/PES2UG22EC085.md

Added PES2UG22EC085.md file to rep

Added PES2UG22EC085.md

---

week0/secB/PES2UG22EC112.md

PES2UG22EC112

---

week0/secB/PES2UG22EC144.md

added file into rep and completed week0

added file into rep

---

week0/secA/PES2UG22EC027.md

PES2UG22EC027

---

week0/secB/pes2ug22ec093.md

created .md file with assignment including name and basic system details.

first assignment

---

week0/secB/PES2UG22EC084.md

Added PES2UG22EC084

---

week0/secB/PES2UG22EC089.md

assignment

---

week0/secB/PES2UG22EC096.md

adding file

---

week0/secA/PES2UG22EC078.md

Completed PES2UG22EC078

---

week0/secA/PES2UG22EC004.md

Submitting my week0 assignment

---

week0/secA/PES2UG22EC024.md

This is my submission for week0.

Added my assignment

---

week0/secA/PES2UG22EC071.md

Submitting Week 0 Assignment

---

week0/secA/PES2UG22EC046.md
week0/secA/PES2UG22EC046.wd

I am subumitting my assignment

---

PES2UG22EC134.md

Assignment Week0 Uploaded

---

PES2UG22EC134.md

Reverts alfadelta10010/COD-Lab#53

File in wrong location

---

week0/secB/PES2UG22EC097.txt

Reverts alfadelta10010/COD-Lab#6

Revert #6 - Wrong file type

---

PES2UG22EC038.md

Reverts alfadelta10010/COD-Lab#16

Revert #16

---

PES2UG22EC052.md

Reverts alfadelta10010/COD-Lab#17

Revert #17

---

week0/secA/PES2UG22EC036.md

week0 file created (finally)

---

week0/secA/PES2UG22EC066.md

this is my week0 assignment  here..

i am adding my assignment

---

week0/secA/PES2UG22EC021.md
week0/secA/Part2.md

Week0 assignment completed 

---

week0/secB/PES2UG22EC114.md

Done with Assignment of week-0

Submitting Assignment

---

week0/secA/PES2UG22EC014.md

This is my submission for week 0.

I have submitted my assignment 

---

week0/secB/PES2UG22EC080.md

Added week0 assignment PES2UG22EC080

PES2UG22EC080.md

---

week0/secA/PES2UG22EC049.md

PES2UG22EC049 WEEK 0 GIT ASSIGNMENT SUBMITTED
PLEASE REVIEW

Submitting my week 0

---

week0/secB/PES2UG22EC149.md

my assignment is done

---

week0/secA/PES2UG22EC007.md

Sorry it was late, but here it is.

assignment0 for week0

---

week0/secA/PES2UG22EC033.md

I did my assignment🫡

---

secA/PES2UG22EC028.md

Reverts alfadelta10010/COD-Lab#76

Revert #76

---

week0/secB/PES2UG22EC137.md

PES2UG22EC137.md

---

week0/secB/PES2UG22EC152.md

assignment0

---

week0/secB/PES2UG22EC087.md

PES2UG22EC087.md

---

week0/secA/PES2UG22EC068.md

file added

---

week0/secB/PES2UG22EC135.md

Sorry misinterpreted your message and am sending this in now, Thanks

 Sorry misinterpreted your message and am sending this in now, Thanks

---

week0/secB/PES2UG22EC097.md
week0/secB/PES2UG22EC097.txt

Sorry for making the wrong file type , I fixed it now.

Fixed File Type 

---

secA/PES2UG22EC028.md
week0/secA/PES2UG22EC028.md

I am done on my Mac M1

---

week0/secB/PES2UG22EC132.md

sorry for the late submission..laptop gone and got a new one
will not happen again
kindly accept<3

Added creds

---

week0/secA/PES2UG22EC052.md

Changed location for srn:052
